{{- if and .Values.server.tlsEnabled (not .Values.server.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "another-ldap-auth.fullname" . }}-tls
  labels:
  {{- include "another-ldap-auth.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{- .Values.server.tlsCert | toYaml | indent 4 }}
  tls.key: {{- .Values.server.tlsKey | toYaml | indent 4 }}
  {{- if .Values.server.tlsCaCert }}
  ca.crt: {{- .Values.server.tlsCaCert | toYaml | indent 4 }}
  {{- end }}
{{- end }}
