{{- if .Values.ldap.tlsCaCert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "another-ldap-auth.fullname" . }}-tls-ldap
  labels:
  {{- include "another-ldap-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: {{- .Values.ldap.tlsCaCert | toYaml | indent 4 }}
{{- end }}
