apiVersion: v1
kind: Secret
metadata:
  name: {{ include "another-ldap-auth.fullname" . }}-tls
  labels:
  {{- include "another-ldap-auth.labels" . | nindent 4 }}
type: kubernetes.io/tls
stringData:
  tls.crt: {{- .Values.server.TlsCert | toYaml | indent 4 }}
  tls.key: {{- .Values.server.TlsKey | toYaml | indent 4 }}
