apiVersion: v1
kind: Service
metadata:
  name: {{ include "another-ldap-auth.fullname" . }}
  labels:
    {{- include "another-ldap-auth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      {{- if .Values.service.port }}
      port: {{ .Values.service.port }}
      {{- else }}
      port: {{ .Values.server.tlsEnabled | ternary 443 80 }}
      {{- end }}
      targetPort: {{ .Values.service.containerPort }}
  selector:
    {{- include "another-ldap-auth.selectorLabels" . | nindent 4 }}
