# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/" # Location of Dockerfile
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/" # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    schedule:
      interval: "weekly"
